site_name: Wikicat Docs
repo_url: https://github.com/xhluca/wikicat
theme: material
nav:
    - Home: 'index.md'
    - 'API Reference':
      - wikicat: 'wikicat.md'
      - wikicat.processing: 'wikicat/processing.md'
      - wikicat.viewer:  'wikicat/viewer.md'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences